### ISSUE TITLE
Crash when building locally 

### ISSUE THREAD

**Issue by Genaro-Chris** [apple/swift-docc#726] opened 2023-10-04 02:44 UTC
While running the following command
``docc preview TSPL.docc``

The application crashes with the following output
```sh
Input: /home/XXX/Desktop/swift-book/TSPL.docc
Template: /home/XXX/Development/swift/usr/share/docc/render

💣 Program crashed: Illegal instruction at 0x000055c67291b1b6

Thread 0 "docc" crashed:

0 DefaultDiagnosticConsoleFormatter.highlightSource(sourceLine:lineNumber:range:) + 342 in docc at /home/build-user/swift-docc/Sources/SwiftDocC/Infrastructure/Diagnostics/DiagnosticConsoleWriter.swift:450:41

zsh: illegal hardware instruction  docc preview TSPL.docc
```

Swift Info
``Swift version 5.9-dev (LLVM df22cff92bb6f9d, Swift fdf50a99df2d1b0)
Target: x86_64-unknown-linux-gnu
/home/genaro/Development/swift/usr/bin/swift-help intro
``

**Comment by d-ronnqvist** [comment] 2023-10-04 04:15
Looks like a dupe of https://github.com/apple/swift-docc/issues/678

**Comment by amartini51** [comment] 2023-10-04 04:15
Moving this to the DocC repository, since it was `docc` that crashed.

@Genaro-Chris Do you know which version of DocC you were running?  It looks like you were building from source?

**Closed by d-ronnqvist** 2023-10-04 04:15 UTC

**Comment by d-ronnqvist** [comment] 2023-10-04 04:17
You should be able to work around the issue by passing `--ide-console-output` as one of the flags to `docc convert`

**Comment by Genaro-Chris** [comment] 2023-10-04 08:29
Thanks
