### ISSUE TITLE
illegal hardware instruction

### ISSUE THREAD

**Issue by unnmd** [apple/swift-docc#892] opened 2024-04-18 08:09 UTC
### Description

Hello everyone!

Swift-DocC is throwing an error:

```
unnmd@unnmdAir swift-book % xcrun docc preview
Input: /Users/unnmd/Development/swift-book
Template: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/docc/render
zsh: illegal hardware instruction  xcrun docc preview
```

I've rebuilt Swift-DocC from the provided repository and still get an error:

```
unnmd@unnmdAir swift-book % DOCC_HTML_DIR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/docc/render docc preview TSPL.docc
Input: /Users/unnmd/Development/swift-book/TSPL.docc
Template: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/docc/render
Swift/StringUTF8View.swift:167: Fatal error: String index is out of bounds
zsh: illegal hardware instruction  DOCC_HTML_DIR= docc preview TSPL.docc
```

The error occurs with Xcode 15.3 (15E204a) and on Xcode 15.4 beta (15F5021i). Both versions use swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4).

In Xcode 15.1, with swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5), there is no such error.

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

**Comment by d-ronnqvist** [comment] 2024-04-18 08:14
This is a dupe of #726 which is a dupe of #678 which was fixed by https://github.com/apple/swift-docc/pull/840 in February.

**Closed by d-ronnqvist** 2024-04-18 08:14 UTC
Labels: bug

**Comment by unnmd** [comment] 2024-04-18 08:30
I apologize, what should I do to avoid this error in the latest version of Swift?

**Comment by d-ronnqvist** [comment] 2024-04-18 08:32
From #726 
> You should be able to work around the issue by passing `--ide-console-output` as one of the flags to `docc convert`

**Comment by unnmd** [comment] 2024-04-18 08:51
Thank you! It worked!
