### ISSUE TITLE
DocC Support on Static Objective-C Library

### ISSUE THREAD

**Issue by justinguo** [apple/swift-docc#416] opened 2022-11-03 23:33 UTC
### Description

I am in an SDK team building Swift/Objective-C libraries.

For Objective-C projects the DocC on Xcode 14.1 generates nothing but API document on Swift based dependency. This is not related to public headers - we have extensive documents available on public headers, which can be shown correctly via `Xcode -> Show Quick Help`.

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

### Expected Behavior

API documentations from public header files can be generated through DocC.

### Actual behavior

API documentations from public header files are not generated through DocC.

### Steps To Reproduce

1. Build a simple Objective-C project with type - Static Library. (Not App)
2. Config the target as XYZ. It should be built without any complaints.
3. Run `xcodebuild -derivedDataPath docsData -scheme XYZ -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max' docbuild`
4. In `docsData/Build/Products/Debug-iphonesimulator`, no document archive file can be found. Only see intermediate artifacts. 

### Swift-DocC Version Information

5.6, 5.7

### Swift Compiler Version Information

```shell
swift-driver version: 1.62.15 Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)
Target: arm64-apple-macosx12.0
```

**Comment by d-ronnqvist** [comment] 2023-12-21 16:50
I can't reproduce this issue with a static library target with public headers (private headers or project visible headers aren't included in documentation for frameworks or libraries).

Regardless, issues about Xcode specific features are out of scope for this repo. If this issue still reproduces for you, please file a [Feedback](http://feedbackassistant.apple.com/) with additional information.

**Closed by d-ronnqvist** 2023-12-21 16:50 UTC
Labels: bug
