### ISSUE TITLE
Building static documentation with xcodebuild fails

### ISSUE THREAD

**Issue by kylebshr** [apple/swift-docc#276] opened 2022-06-03 18:36 UTC
Building static documentation for a framework using a workspace generated with Cocoapods can fail if it has dependencies.

### Checklist
- [x] If possible, I've reproduced the issue using the `main` branch of this package.
- [x] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

### Expected behavior

Generating static documentation for a framework in an xcworkspace should succeed.

### Actual behavior

The documentation fails to build with `** BUILD DOCUMENTATION FAILED **`.

### Steps to Reproduce

A project reproducing this issue is available at https://github.com/kylebshr/docc-fail. It contains:

- A lightweight Xcode project
- A podspec for a framework called `Core` that has some dependencies
- A Podfile that adds `Core` as a dependency to the Xcode project
- The generated Workspace is checked in as `docc-fail.xcworkspace`

To reproduce this issue, I first build the scheme `Core`, which succeeds, then attempt to build documentation using `xcodebuild`:

```
xcodebuild build -scheme Core \
    -workspace docc-fail.xcworkspace \
    -destination generic/platform=iOS

xcodebuild docbuild -scheme Core \
    -workspace docc-fail.xcworkspace \
    -destination generic/platform=iOS \
    OTHER_DOCC_FLAGS="--transform-for-static-hosting --output-path ../docs --hosting-base-path docs"
```

### Swift-DocC Version Information

**Swift-DocC version:** I'm using Xcode 13.4. This also happened on Xcode 13.3.
**Swift Compiler version:** 
```
swift-driver version: 1.45.2 Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)
Target: arm64-apple-macosx12.0
```

**Comment by d-ronnqvist** [comment] 2022-06-03 18:48
Other than needing to update the code signing settings, I can not reproduce this build failure.

Are you able to share more information about the error that you're encountering?

**Comment by kylebshr** [comment] 2022-06-03 19:00
Certainly - here's the output when I run it! I'm on an M1 computer, I wonder if there are differences there?

```
➜  docc-fail git:(main) xcodebuild docbuild -scheme Core \                      
        -workspace docc-fail.xcworkspace \
        -destination generic/platform=iOS \
        OTHER_DOCC_FLAGS="--transform-for-static-hosting --output-path ../docs --hosting-base-path docs"
2022-06-03 11:59:16.434 xcodebuild[10960:3200087] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-06-03 11:59:16.434 xcodebuild[10960:3200087] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild docbuild -scheme Core -workspace docc-fail.xcworkspace -destination generic/platform=iOS "OTHER_DOCC_FLAGS=--transform-for-static-hosting --output-path ../docs --hosting-base-path docs"

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

Build settings from command line:
    OTHER_DOCC_FLAGS = --transform-for-static-hosting --output-path ../docs --hosting-base-path docs

note: Using new build system
note: Planning
Create build description
Build description signature: 0544e9c57310a8fc9d0e568848b5a346
Build description path: /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Intermediates.noindex/XCBuildData/0544e9c57310a8fc9d0e568848b5a346-desc.xcbuild

note: Build preparation complete
note: Building targets in dependency order
WriteAuxiliaryFile /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/BlueprintUI.build/BlueprintUI-all-target-headers.hmap (in target 'BlueprintUI' from project 'Pods')
    cd /Users/kbashour/Development/docc-fail/Pods
    write-file /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/BlueprintUI.build/BlueprintUI-all-target-headers.hmap

WriteAuxiliaryFile /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/BlueprintUICommonControls.build/BlueprintUICommonControls-all-target-headers.hmap (in target 'BlueprintUICommonControls' from project 'Pods')
    cd /Users/kbashour/Development/docc-fail/Pods
    write-file /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/BlueprintUICommonControls.build/BlueprintUICommonControls-all-target-headers.hmap

ProcessInfoPlistFile /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Products/Debug-iphoneos/BlueprintUI/BlueprintUI.framework/Info.plist /Users/kbashour/Development/docc-fail/Pods/Target\ Support\ Files/BlueprintUI/BlueprintUI-Info.plist (in target 'BlueprintUI' from project 'Pods')
    cd /Users/kbashour/Development/docc-fail/Pods
    builtin-infoPlistUtility /Users/kbashour/Development/docc-fail/Pods/Target\ Support\ Files/BlueprintUI/BlueprintUI-Info.plist -producttype com.apple.product-type.framework -expandbuildsettings -format binary -platform iphoneos -requiredArchitecture arm64 -o /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Products/Debug-iphoneos/BlueprintUI/BlueprintUI.framework/Info.plist

CompileDocumentation (in target 'BlueprintUI' from project 'Pods')
    cd /Users/kbashour/Development/docc-fail/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/docc convert --index --fallback-display-name BlueprintUI --fallback-bundle-identifier org.cocoapods.BlueprintUI --fallback-bundle-version 1 --output-dir /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Products/Debug-iphoneos/BlueprintUI/BlueprintUI.doccarchive --emit-fixits --transform-for-static-hosting --output-path ../docs --hosting-base-path docs --additional-symbol-graph-dir /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/BlueprintUI.build/symbol-graph
/Users/kbashour/Development/docc-fail/Pods/BlueprintUI/BlueprintUI/Sources/Focus/FocusState.swift:60:86: warning: Topic reference 'TextField' couldn't be resolved. No local documentation matches this reference.

Ld /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Products/Debug-iphoneos/BlueprintUICommonControls/BlueprintUICommonControls.framework/BlueprintUICommonControls normal (in target 'BlueprintUICommonControls' from project 'Pods')
    cd /Users/kbashour/Development/docc-fail/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios12.0 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk -L/Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Products/Debug-iphoneos/BlueprintUICommonControls -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk/usr/lib/swift -F/Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Products/Debug-iphoneos/BlueprintUICommonControls -F/Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Products/Debug-iphoneos/BlueprintUI -filelist /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/BlueprintUICommonControls.build/Objects-normal/arm64/BlueprintUICommonControls.LinkFileList -install_name @rpath/BlueprintUICommonControls.framework/BlueprintUICommonControls -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/BlueprintUICommonControls.build/Objects-normal/arm64/BlueprintUICommonControls_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fembed-bitcode-marker -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/BlueprintUICommonControls.build/Objects-normal/arm64/BlueprintUICommonControls.swiftmodule -framework BlueprintUI -weak_framework SwiftUI -framework Foundation -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/BlueprintUICommonControls.build/Objects-normal/arm64/BlueprintUICommonControls_dependency_info.dat -o /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Products/Debug-iphoneos/BlueprintUICommonControls/BlueprintUICommonControls.framework/BlueprintUICommonControls

WriteAuxiliaryFile /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ListableUI.build/ListableUI-all-target-headers.hmap (in target 'ListableUI' from project 'Pods')
    cd /Users/kbashour/Development/docc-fail/Pods
    write-file /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ListableUI.build/ListableUI-all-target-headers.hmap

CompileDocumentation (in target 'BlueprintUICommonControls' from project 'Pods')
    cd /Users/kbashour/Development/docc-fail/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/docc convert --index --fallback-display-name BlueprintUICommonControls --fallback-bundle-identifier org.cocoapods.BlueprintUICommonControls --fallback-bundle-version 1 --output-dir /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Products/Debug-iphoneos/BlueprintUICommonControls/BlueprintUICommonControls.doccarchive --emit-fixits --transform-for-static-hosting --output-path ../docs --hosting-base-path docs --additional-symbol-graph-dir /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/BlueprintUICommonControls.build/symbol-graph
Error: “267CA626-D997-4F70-BF18-EC9D42975997-10969-000004567EA8ACF2” couldn’t be moved to “docc-fail”.
Command CompileDocumentation failed with a nonzero exit code

WriteAuxiliaryFile /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/BlueprintUILists.build/BlueprintUILists-all-target-headers.hmap (in target 'BlueprintUILists' from project 'Pods')
    cd /Users/kbashour/Development/docc-fail/Pods
    write-file /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/BlueprintUILists.build/BlueprintUILists-all-target-headers.hmap

WriteAuxiliaryFile /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ListableUI-ListableUIResources.build/ListableUIResources-all-target-headers.hmap (in target 'ListableUI-ListableUIResources' from project 'Pods')
    cd /Users/kbashour/Development/docc-fail/Pods
    write-file /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ListableUI-ListableUIResources.build/ListableUIResources-all-target-headers.hmap

ProcessInfoPlistFile /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Products/Debug-iphoneos/ListableUI/ListableUIResources.bundle/Info.plist /Users/kbashour/Development/docc-fail/Pods/Target\ Support\ Files/ListableUI/ResourceBundle-ListableUIResources-ListableUI-Info.plist (in target 'ListableUI-ListableUIResources' from project 'Pods')
    cd /Users/kbashour/Development/docc-fail/Pods
    builtin-infoPlistUtility /Users/kbashour/Development/docc-fail/Pods/Target\ Support\ Files/ListableUI/ResourceBundle-ListableUIResources-ListableUI-Info.plist -producttype com.apple.product-type.bundle -expandbuildsettings -format binary -platform iphoneos -requiredArchitecture arm64 -o /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Products/Debug-iphoneos/ListableUI/ListableUIResources.bundle/Info.plist

WriteAuxiliaryFile /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Core.build/Core-all-target-headers.hmap (in target 'Core' from project 'Pods')
    cd /Users/kbashour/Development/docc-fail/Pods
    write-file /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Core.build/Core-all-target-headers.hmap

CompileDocumentation (in target 'ListableUI' from project 'Pods')
    cd /Users/kbashour/Development/docc-fail/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/docc convert --index --fallback-display-name ListableUI --fallback-bundle-identifier org.cocoapods.ListableUI --fallback-bundle-version 1 --output-dir /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Products/Debug-iphoneos/ListableUI/ListableUI.doccarchive --emit-fixits --transform-for-static-hosting --output-path ../docs --hosting-base-path docs --additional-symbol-graph-dir /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ListableUI.build/symbol-graph
/Users/kbashour/Development/docc-fail/Pods/ListableUI/ListableUI/Sources/ReappliesToVisibleView.swift:57:83: warning: Topic reference 'ItemContent/isEquivalent(to:)' couldn't be resolved. No local documentation matches this reference.
/Users/kbashour/Development/docc-fail/Pods/ListableUI/ListableUI/Sources/Item/ItemContent.swift:200:13: warning: Topic reference 'ItemContent/identifierValue-swift.property' couldn't be resolved. No local documentation matches this reference.
/Users/kbashour/Development/docc-fail/Pods/ListableUI/ListableUI/Sources/Item/ItemContent.swift:203:65: warning: Topic reference 'ItemContent/identifierValue-swift.property' couldn't be resolved. No local documentation matches this reference.
/Users/kbashour/Development/docc-fail/Pods/ListableUI/ListableUI/Sources/Item/ItemContent.swift:213:49: warning: Topic reference 'ItemContent/identifierValue-swift.property' couldn't be resolved. No local documentation matches this reference.
/Users/kbashour/Development/docc-fail/Pods/ListableUI/ListableUI/Sources/EmbeddedList.swift:295:44: warning: Topic reference 'Equatable' couldn't be resolved. No local documentation matches this reference.
/Users/kbashour/Development/docc-fail/Pods/ListableUI/ListableUI/Sources/ReappliesToVisibleView.swift:54:96: warning: Topic reference 'ItemContent/isEquivalent(to:)' couldn't be resolved. No local documentation matches this reference.
/Users/kbashour/Development/docc-fail/Pods/ListableUI/ListableUI/Sources/Item/ItemContent.swift:539:47: warning: Topic reference 'ItemContent/identifier' couldn't be resolved. No local documentation matches this reference.
/Users/kbashour/Development/docc-fail/Pods/ListableUI/ListableUI/Sources/Item/ItemContent.swift:49:50: warning: Topic reference 'ItemContent/identifierValue-swift.property' couldn't be resolved. No local documentation matches this reference.
/Users/kbashour/Development/docc-fail/Pods/ListableUI/ListableUI/Sources/Item/ItemContent.swift:52:13: warning: Topic reference 'ItemContent/identifierValue-swift.property' couldn't be resolved. No local documentation matches this reference.
/Users/kbashour/Development/docc-fail/Pods/ListableUI/ListableUI/Sources/Item/ItemContent.swift:55:13: warning: Topic reference 'ItemContent/identifierValue-swift.property' couldn't be resolved. No local documentation matches this reference.
/Users/kbashour/Development/docc-fail/Pods/ListableUI/ListableUI/Sources/Item/ItemContent.swift:295:44: warning: Topic reference 'Equatable' couldn't be resolved. No local documentation matches this reference.
/Users/kbashour/Development/docc-fail/Pods/ListableUI/ListableUI/Sources/EmbeddedList.swift:200:13: warning: Topic reference 'ItemContent/identifierValue-swift.property' couldn't be resolved. No local documentation matches this reference.
/Users/kbashour/Development/docc-fail/Pods/ListableUI/ListableUI/Sources/EmbeddedList.swift:203:65: warning: Topic reference 'ItemContent/identifierValue-swift.property' couldn't be resolved. No local documentation matches this reference.
/Users/kbashour/Development/docc-fail/Pods/ListableUI/ListableUI/Sources/EmbeddedList.swift:213:49: warning: Topic reference 'ItemContent/identifierValue-swift.property' couldn't be resolved. No local documentation matches this reference.
/Users/kbashour/Development/docc-fail/Pods/ListableUI/ListableUI/Sources/Item/ItemContent.swift:539:47: warning: Topic reference 'ItemContent/identifier' couldn't be resolved. No local documentation matches this reference.

ProcessInfoPlistFile /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Products/Debug-iphoneos/ListableUI/ListableUI.framework/Info.plist /Users/kbashour/Development/docc-fail/Pods/Target\ Support\ Files/ListableUI/ListableUI-Info.plist (in target 'ListableUI' from project 'Pods')
    cd /Users/kbashour/Development/docc-fail/Pods
    builtin-infoPlistUtility /Users/kbashour/Development/docc-fail/Pods/Target\ Support\ Files/ListableUI/ListableUI-Info.plist -producttype com.apple.product-type.framework -expandbuildsettings -format binary -platform iphoneos -requiredArchitecture arm64 -o /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Products/Debug-iphoneos/ListableUI/ListableUI.framework/Info.plist

CompileDocumentation (in target 'Core' from project 'Pods')
    cd /Users/kbashour/Development/docc-fail/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/docc convert --index --fallback-display-name Core --fallback-bundle-identifier org.cocoapods.Core --fallback-bundle-version 1 --output-dir /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Products/Debug-iphoneos/Core/Core.doccarchive --emit-fixits --transform-for-static-hosting --output-path ../docs --hosting-base-path docs --additional-symbol-graph-dir /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Core.build/symbol-graph

CpResource /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Products/Debug-iphoneos/ListableUI/ListableUI.framework/ListableUIResources.bundle /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Products/Debug-iphoneos/ListableUI/ListableUIResources.bundle (in target 'ListableUI' from project 'Pods')
    cd /Users/kbashour/Development/docc-fail/Pods
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Products/Debug-iphoneos/ListableUI/ListableUIResources.bundle /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Products/Debug-iphoneos/ListableUI/ListableUI.framework

Ld /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Products/Debug-iphoneos/BlueprintUILists/BlueprintUILists.framework/BlueprintUILists normal (in target 'BlueprintUILists' from project 'Pods')
    cd /Users/kbashour/Development/docc-fail/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios12.0 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk -L/Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Products/Debug-iphoneos/BlueprintUILists -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk/usr/lib/swift -F/Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Products/Debug-iphoneos/BlueprintUILists -F/Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Products/Debug-iphoneos/BlueprintUI -F/Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Products/Debug-iphoneos/ListableUI -filelist /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/BlueprintUILists.build/Objects-normal/arm64/BlueprintUILists.LinkFileList -install_name @rpath/BlueprintUILists.framework/BlueprintUILists -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/BlueprintUILists.build/Objects-normal/arm64/BlueprintUILists_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fembed-bitcode-marker -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/BlueprintUILists.build/Objects-normal/arm64/BlueprintUILists.swiftmodule -framework BlueprintUI -framework ListableUI -weak_framework SwiftUI -framework Foundation -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/BlueprintUILists.build/Objects-normal/arm64/BlueprintUILists_dependency_info.dat -o /Users/kbashour/Library/Developer/Xcode/DerivedData/docc-fail-aqkuisnswoabsuceipozbtyivhzn/Build/Products/Debug-iphoneos/BlueprintUILists/BlueprintUILists.framework/BlueprintUILists

** BUILD DOCUMENTATION FAILED **


The following build commands failed:
	CompileDocumentation (in target 'BlueprintUICommonControls' from project 'Pods')
(1 failure)
➜  docc-fail git:(main) 
```

**Comment by d-ronnqvist** [comment] 2022-06-03 22:00
Thanks. Now I see what the issue is. Both targets are trying to output to the same folder and the second call is failing because the output from the first call is already there. 

This happens because `--output-path` is passed in the `OTHER_DOCC_FLAGS` build setting override which applies to all targets in the build, meaning that all calls to `docc` are told to write to the same location. After removing that argument from the Other DocC flags the build should pass. 

If you want to find the built .doccarchive outputs from an `xcodebuild docbuild` call on the command line you can use `find` to search for a specific documentation archive in the products build folder.

Since this is about Xcode/xcodebuild I'm going to close this issue here. If you have feature request or enhancement request for DocC in Xcode, we'd love to hear about your use cases and workflows via <https://feedbackassistant.apple.com>.

**Closed by d-ronnqvist** 2022-06-03 22:00 UTC
Labels: bug, question
